### PR TITLE
Implement links in exported PDFs

### PR DESCRIPTION
**Pull request by ForeverRainbow**
This is the second part to #942

Image anchors are now processed, anchors are inserted as the unicode anchor emoji (⚓) instead of the image because it was simpler, since it takes a `CtImageAnchor` in the relevant ctor however, this is easy to change. 

This adds two new classes, `CtDestPrintable` and `CtLinkPrintable` where `CtDestPrintable` is what processes `CtImageAnchor`'s, and `CtLinkPrintable` just applies the cairo link tag and makes its text blue.

Internal destinations are represented in the form `n.<node id>.[section (e.g h1-1)]`, the section part is optional. External destinations are processed by `CtStrUtil::external_uri_from_internal()` which converts an internal uri (e.g `webs https://example.com`) to an external one (and decodes file paths).

### CODE REVIEW

**Comment by txe** [comment]
Amazing, thanks!

**Comment by giuspen** [comment]
Indeed this was a very much awaited feature, many thanks!

**Comment by ForeverRainbow** [comment]
I think the windows build of this is still broken

**Comment by txe** [comment]
it's ok, I'll fix it later

**Comment by txe** [comment]
looks like CppUTest is built on Win32 without the Standard C++ Library, so just disabled CHECK_THROWS there

**Pull request merged**
