### PR TITLE
Correct the Fedora build instructions

### PR DESCRIPTION
**Pull request by funnelfiasco**
Specifically, add the `make` step to perform the build and remove some unnecessary directory changes.

### CODE REVIEW

**Comment by txe** [comment]
It's quite bad idea, cmake recommendations explicitly say not to use source dir as bulid dir. And though it's possible, it shouldn't be in README.

**Comment by funnelfiasco** [comment]
I'm not very experienced with cmake, so I wasn't aware of that. But the README is still missing the `make` step. The instructions as written don't produce a binary.

**Comment by txe** [comment]
Ah, yes, you're right. Would you like to make a PR? :)

**Comment by funnelfiasco** [comment]
Yep, testing it now to make sure I have the directories correct. I don't have other OSes handy to test on, but I assume all of the Linuxes will need the same edit.

**Comment by txe** [comment]
Right

**Pull request closed without merging**
