### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by slichtzzz**
Update Russian translation

### CODE REVIEW

**Comment by slichtzzz** [comment]
I hope so )

**Comment by slichtzzz** [comment]
We can discuss it then. I bet it's the translation of "node" )
Why do you call it "ветвь", which is actually a branch, by the way? Looks kind of disappointing to me…

**Comment by Camilot55** [comment]
I know how "node" is translated, but in this case there is an association with a cherry tree, and unfortunately it has branches. I will take your comments into account in the next edition!

**Comment by slichtzzz** [comment]
Ok! But it why put this association in translation, when there is no such an association in the original? I think the author of CherryTree didn't call the nodes "branches" for a reason…

**Comment by Camilot55** [comment]
It's like an idiom. It is raining cats and dogs. 
We can discuss this topic a lot, I said that I will take into account some of your comments in the next edition. And so let's say how many people have so many opinions. But the translation from English to Russian should not be verbatim, the main thing is to convey the meaning.  All the best to you.

**Comment by slichtzzz** [comment]
Yes. Tranlsation should not be verbatim when it comes to poetry, but it should be as accurate as possible when it comes to math. But of course you are entitled to have your own opinion. I wish you all the best and hope that at least some of my work will be found useful! Good luck!

**Comment by giuspen** [comment]
@Camilot55 I'm releasing in a couple of days and I would like the Russian language to be up to date,  if you are busy at the moment maybe @slichtzzz can help this time?
(just run `./po/i18n_pot_to_updated_po.py` to pull the latest sentences needed for the upcoming release)

**Comment by Camilot55** [comment]
Hi Giuseppe.I see that you doubt my translation. If you are not satisfied with my translation, you can choose another translator. This is your legal right. But I have all three languages tied together.  In my translation, I deviate a little from the rules and do not use machine translation, but try to convey the meaning. This is what my teachers taught me.  I'm sorry that I let you doubt me.  07.06.2023, 00:39, "Giuseppe Penone" ***@***.***>***@***.*** I'm releasing in a couple of days and I would like the Russian language to be up to date, if you are busy at the moment maybe @slichtzzz can help this time?(just run ./po/i18n_pot_to_updated_po.py to pull the latest sentences needed for the upcoming release)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>  -- С уважением,Виктор Полянский +7(932) 207-49-55 Whatsapp +79322074955Viber         +79322074955

**Comment by giuspen** [comment]
@Camilot55 I have no doubt/objection at all your work is great I just need the update ASAP because I'm about to release. Didn't mean to offend you, apologies. I will wait for you.

**Pull request closed without merging**
