### PR TITLE
100% ru.po and kk_KZ.po and new lang kz_Latyn.po

### PR DESCRIPTION
**Pull request by Camilot55**
Updated languages (Russian, Kazakh), fixed translation errors

### CODE REVIEW

**Comment by Camilot55** [comment]
Updated languages  Kazakh fixed translation errors

**Comment by Camilot55** [comment]
Hi Giuseppe. I also want to add the Kazakh language (Latin). I think I'll finish the translation today. I will add a comit.

**Comment by giuspen** [comment]
Also note that the name kz_Latyn is not standard. I've been searching but cannot find anything, I suggest for now we call it "kk_LA" as kk is the standard Kazakh prefix, is that ok?

**Comment by Camilot55** [comment]
Hi Giuseppe. I checked everything, everything is fine, there are no untranslated lines (see the screenshot).
kk_LA - yes it's OK. It's just that this language is still being introduced in Kazakhstan. It will be fully translated into Latin soon. They already teach in schools.
kk_KZ
kk_Latyn
ru

**Comment by Camilot55** [comment]
I see you have new lines to translate, which I don't have in the *.po files

**Comment by giuspen** [comment]
Hi Viktor you have to run from the po folder i18n_pot_to_updated_po.py or just use the files that I sent you by email.

**Comment by Camilot55** [comment]
New files have been sent to the mail, I will deal with them as soon as possible. You can delete this comit. I had files to translate cherrytree 0.99.49. So we will refine.

**Comment by Camilot55** [comment]
I'm closing the pulll

**Pull request closed without merging**
