### PR TITLE
Implement Command Palette Feature

### PR DESCRIPTION
**Pull request by ksmukta**
**Preview**: cherrytree-command-pallete
**Keybinding**: Ctrl+Shift+P
Currently all the menu items are shown in the command palette. User can search the palette by simply focusing and then typing in palette dialog window.
The search used is sub sequence search on lower cased strings.
**Note**: Ctrl+Shift+P was earlier used for PrintPageSetup but now its used for Command Pallete

### CODE REVIEW

**Comment by giuspen** [comment]
The sub sequence search does not work for me (linux mint cinnamon latest), the search works only if you start typing from the very first letter but worse than the default search function.

**Comment by ksmukta** [comment]
Could you please share some GIF to show how it does not work, Becuase for me it works fine(on Ubuntu 18.04).
command_palette_subsequence

**Comment by giuspen** [comment]
Just try and type "pal", I expect "Command Palette" below to be focused, which it does not

**Comment by txe** [comment]
For me, "tohtml" works on Ubuntu, later I can take a look on Arch.

**Comment by txe** [comment]
The issue is with `is_subsequence`, which just checks individual letters , not as the whole text. I suggest to use something like this:
```python
data = data.tolower().replace(" ", "")
query = query.tolower().replace(" ", "")
return data.find(query) != -1
```

**Comment by ksmukta** [comment]
Yes, need to update the search function.

**Comment by ksmukta** [comment]
#622 
Fixed on this.
Thanks @txe for the code. Nice Idea.

**Comment by ksmukta** [comment]
Currently the strings shown in command palette are using "dn"(description) from menudict. Can you help me how to use "sd"(short description). If I try to use "sd", the keys come with underscores like this: 

**New _Instance**, instead of **New Instance**

**Comment by giuspen** [comment]
Those underscores are to generate so called accelerators, to quickly access the menu items using only the keyboard. There is a method to enable these accelerators, I'll see if I can find it browsing from my phone and get back to you

**Comment by giuspen** [comment]
https://developer.gnome.org/pygtk/stable/class-gtkmenuitem.html I may have remembered wrong, try the set_use_underscore

**Pull request merged**
