### PR TITLE
Improve realtime markdown formatting

### PR DESCRIPTION
**Pull request by ForeverRainbow**
This is an improvement for realtime markdown formatting. It also adds some bits of syntax which I had forgotten :p

Markdown formatting will now be applied automatically when valid tags are matched. The tags will be removed and the cursor placed at the end of the newly formatted block. So \_italic\_ would become _italic_ as soon as the last \_ was typed. Currently there is no way to undo this, `undo` will remove the entire format block at once. I am not sure how undo actually works so I am assuming there is a way around this but not sure how to implement it. 

Tables have been disabled due to not being able to be closed (thereby locking the parser until a restart). They still work when importing. Also headers with `==` and `---` do not work for obviouse reasons.

I also added `<some url>` for links. I am going to do a writeup of what markdown cherrytree supports, should I just place this in `/future`? (can also serve as a demonstraction of the markdown importer)

Ref #858

### CODE REVIEW

**Comment by ForeverRainbow** [comment]
Currently this doesnt check if the node is rich text before applying, oops - fixing it now

**Comment by txe** [comment]
I'd like you to change your code related to CtTextView:
- there is a lot of code in CtTextView for markdown, encapsulate it by putting in e.g. CtMardowBuffer. 
- there is a lot `_pCtMainWin->get_ct_config()->enableMdFormatting && _buffer_is_rich_text()`. Add `enable(bool enable)` instead.
- please don't use functions without namespace, e.g. `get_md_tag_name`. Use lambdas or put them in a class.
- `apply_tag` creates CT tags or your custom tags? if it's CT's, then use `get_text_tag_name_exist_or_create`. If custom ones, then I 'm not sure if CT can handle them properly in different situations.
- functions for signals usually have a pattern in the name like `_on_key_press_event`

**Comment by ForeverRainbow** [comment]
`apply_tag` is a helper to apply or create a custom tag yes. I don't think it should cause issues since the names follow the patten `md-formatting-<num>`. If that is going to cause an issue then I will have to rethink how to do this. Also I went with the `_for` patten with the signal handlers since thats what the other ones in the class seem to do (although they are called manually from CtMainWin), so I will change those

**Comment by ForeverRainbow** [comment]
@txe I'm refractoring the markdown stuff into `CtMarkdownFilter` is just attached to an arbratray `Gtk::TextBuffer`, should I keep it in `ct_widgets` or move it (e.g into `ct_parser`)?

**Comment by txe** [comment]
well, ct_parser sounds good

**Comment by txe** [comment]
I will need to test changes before emerging them

**Comment by giuspen** [comment]
Doesn't build on Mac OS https://travis-ci.com/github/giuspen/cherrytree

**Comment by giuspen** [comment]
@txe I have not looked at this because you said that you were going to test it in a previous comment but if you are busy and/or would prefer me to look at it instead I will try and give feedback to @ForeverRainbow myself as soon as get some time

**Comment by txe** [comment]
Thanks, it would be great!

**Comment by giuspen** [comment]
@ForeverRainbow I'm sorry I kept your PR in standby so long that it started to have conflicts. It's good to go for me though so if you resolve the conflicts I'm going to merge straight away

**Comment by ForeverRainbow** [comment]
Conflicts seem to be purely consmetic, weird

**Comment by giuspen** [comment]
Thanks!

**Pull request merged**
