### PR TITLE
Add CSV handling to CtTable in the C++ port

### PR DESCRIPTION
**Pull request by ForeverRainbow**
Supports excel style csv with comma field delims and double quotes for strings.

The reason it for the ugly code in `from_csv` where it reads the data in chunks is because it needs to be able to handle newlines in cells

### CODE REVIEW

**Comment by giuspen** [comment]
The Windows build is behaving strangely after I made it build in Debug so no panic if it keeps failing I'll switch back to Release

**Comment by txe** [comment]
`row_to_csv` is not good, text can have " or \n or maybe something else, any of that breaks csv format.

**Comment by ForeverRainbow** [comment]
The newline is not an issue since it gets escaped into a string anyway, the `"` is an issue

**Comment by txe** [comment]
the same thing with reading, do you support escaping " (like \")? because it's quite often used.

Also, it's not easy to test, I'd prefer to have vectors of string vectors to read/write. It will be double job to convert them to matrix, but it's easy to test.

**Comment by ForeverRainbow** [comment]
Working on escaping now, I can split `from_csv` into public methods which return `CtTableRow`, `CtTableCell` and `CtTableMatrix` which can be used for testing?

**Comment by ForeverRainbow** [comment]
Also what do you mean by 
> vectors of strings to read/write
?

**Comment by txe** [comment]
all classes you named create buffers and do a lot of work which currently hard to fake in tests. And idea is to test how csv reading\writing works because it's can have issues.

As I see, there will be one function which reads a file and creates vector<vector<string>>. The result is used to create matrix. You can wrap it up in one function call  `from_csv`

Same thing with converting matrix to csv.

**Comment by ForeverRainbow** [comment]
Ah I see, so create a matrix of the cell contents before wrapping them into `CtTableCell`, I agree thats much cleaner :p

**Comment by txe** [comment]
can you put CtCSV in ct_misc, so ct_table will be cleaner? Then I accept this PR

**Comment by ForeverRainbow** [comment]
@txe Makes more sense in `ct_parser`?

**Comment by txe** [comment]
No, I would put it in ct_parser if it was based on ctparser. It just a couple of functions to read/write csv file.

**Comment by txe** [comment]
Thanks

**Pull request merged**
