### PR TITLE
Fix German translation

### PR DESCRIPTION
**Pull request by basicmaster**

### CODE REVIEW

**Comment by giuspen** [comment]
Thanks!

**Comment by giuspen** [comment]
@basicmaster would you be available to become the new maintainer for the German language and be contacted by me in future before the next releases?

**Comment by basicmaster** [comment]
Yes, I would enjoy doing that. I just need to be nudged to update the translation, when needed (as you announce). Except of course if I notice needed updates myself - in the present case, I saw the "TO BE UPDATED" hint on your homepage.

**Comment by giuspen** [comment]
Great, thank you!

**Comment by giuspen** [comment]
Can you give me an email I can use to notify you? f yes tell me if you are happy with that email to be associated to you on the translators credits or you would rather not

**Comment by basicmaster** [comment]
Yes, please use "basic.master" together with the hostname "gmx.de" ;-) For the translators credits, you can use my real name (see profile).

**Comment by giuspen** [comment]
Excellent!

**Pull request merged**
