### PR TITLE
New Main menu and new ru translate

### PR DESCRIPTION
**Pull request by Camilot55**
Hi Giuseppe.
I corrected the translation and cleaned up the file from unnecessary comments.
I will make a more accurate translation when version 0.99.31 is released.
It's easier for me to translate when there is a new version of the program before my eyes.
I also send suggestions for the layout of the new main menu (requests from my employees).
I will make the application settings menu a little later, as I need to see your innovations.

### CODE REVIEW

**Comment by giuspen** [comment]
The changes in ct_menu.cc are huge and include various code style changes such as added spaces.
Those style changes may also make sense but here please focus on surgically minimum changes.
Please restart from the latest ct_menu.cc and surgically apply the minimum changes you would like me to evaluate.

**Comment by Camilot55** [comment]
Okay, I'll check it out soon.
But I propose to change ct_menu.cc significantly, remove duplicates and make it more understandable.
Brevity is the soul of wit.
Translation proposal, sometimes the Russian language requires not to translate literally, but to convey only the meaning that will be understandable to a Russian person.
I hope you understand what I mean.
Thanks.

**Comment by giuspen** [comment]
The plan is to not touch translatable strings for the next release since there are various small issues to sort out anyway, so please wait for that. If you want to rework ok but please explain your goal.

**Comment by giuspen** [comment]
Reason to hang on with translatable changes is to not bug the translators every release

**Comment by Camilot55** [comment]
I will try to make minimal changes. The goal is to improve your application and make it more usable and performant. Such are the wishes of our employees of the Nuclear Center.

**Comment by Camilot55** [comment]
Hi Giuseppe, this PR has been closed, I will open a new one soon

**Comment by giuspen** [comment]
Hi Victor OK cheers

**Pull request closed without merging**
