### PR TITLE
Перевод на русский

### PR DESCRIPTION
**Pull request by Camilot55**
Изменил файл ru.po. Изменил переводчика в файле ct_dialogs.cc.  Вы использовали мой перевод отправленный вам по почте, но в разработчики не поставили

### CODE REVIEW

**Comment by giuspen** [comment]
I cannot merge this, Andrij is in charge with the Russian translation, you have to talk with him and ask him if he is happy to pass to you the Russian language. You know his email please write to him.

**Comment by Camilot55** [comment]
Please tell me how to open the cyerrytree project in Visual Studio 2019 or Visual Studio Code for testing and editing forms and dialogs?

**Comment by Camilot55** [comment]
Write to email camilot55@yandex.ru

**Comment by giuspen** [comment]
it is described at https://github.com/giuspen/cherrytree/blob/master/README.md (visual studio code)

**Comment by Camilot55** [comment]
does not work

**Comment by giuspen** [comment]
What is not working

**Comment by Camilot55** [comment]
I will write to you by mail and send a screen and a log

**Comment by giuspen** [comment]
Хорошо

**Comment by giuspen** [comment]
Ok Andrei wrote to me that he is happy to pass to you the Russian translation. He also told me that he advised you few corrections. Please let me know if you are going to apply changes or I shall merge the translation as is. Thanks!

**Comment by Camilot55** [comment]
Добрый день. Я внесу несколько изменений и Вам сообщу 15.01.2021, 00:42, "Giuseppe Penone" <notifications@github.com>: Ok Andrei wrote to me that he is happy to pass to you the Russian translation. He also told me that he advised you few corrections. Please let me know if you are going to apply changes or I shall merge the translation as is. Thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С уважением,Виктор Полянский +7(932) 207-49-55 Whatsapp +79322074955Viber         +79322074955

**Comment by giuspen** [comment]
Хорошо спасибо ;)

**Comment by Camilot55** [comment]
Исправил ошибки и добавил недостающие переводы некоторых сабменю

**Comment by giuspen** [comment]
Большое спасибо

**Comment by Camilot55** [comment]
Незачто, Вам спасибо. Я постоянно отслеживаю вашу программу. Есть предложения по настройки интерфейса, но никак не могу запустить проект в Microsoft Visual Studio 2019 или Visual Studio Code

**Comment by giuspen** [comment]
You don't need visual studio code, you just need a terminal and a text editor (I actually use geany).
See https://github.com/giuspen/cherrytree/blob/master/README.md for the commands.
Visual Studio Code is handy to debug but I often do it from the terminal with gdb instead

**Pull request merged**
