### PR TITLE
bugfix - status icon (missing / bad render) #1703 and tree node visibility #1704

### PR DESCRIPTION
**Pull request by gh9000**
Pull request to address Cherrytree Issue #1703 & #1704.

### CODE REVIEW

**Comment by giuspen** [comment]
Thanks @gh9000

**Comment by giuspen** [comment]
the problem is that now I have the system tray icon out even if I configured it off

**Comment by giuspen** [comment]
I'm going to sort it out anyway no worries

**Comment by gh9000** [comment]
I think I just fixed it, but I want to do a proper build outside VSCodium and install to test.

Based on a quick test, it looks like simply adding code to explicittly set the StatusIcon visibility to false works:

        // show status icon if it's needed and also check if systray exists
        if (_pCtConfig->systrayOn) {
            _pGtkStatusIcon->set_visible(true);
        }
        else {                                                              // New code
            _pGtkStatusIcon->set_visible(false);         // New code
        }                                                                     // New code 
    }

**Comment by giuspen** [comment]
Yes but this way it blinks on the systray at the start which I would like to avoid. I'm thinking instead to slightly complicate the code to do not instantiate at all the status icon unless needed. The pointer is null if not yet instantiated and that will be handled. It will still never hide the systray when instantiating which I understand causes issues

**Comment by giuspen** [comment]
Leave this to me and don't worry about the complication I appreciate you got rid of that critical Gtk error message

**Comment by gh9000** [comment]
My ego is not hurt at all. 

I fully expected you to find better ways to handle the issues. I'm not a Gtk / C++ guy at all. I just thought I'd dig around in the code and give some food for thought to potential fixes rather than just throwing up  a bug report.

I also learned something about interacting with GitHub projects. I've only used  git locally before now. 

Thank you for looking into it so quickly.

**Pull request merged**
