### PR TITLE
Updated the file with comments and a new cherrytree.pot

### PR DESCRIPTION
**Pull request by Camilot55**
Added a menu for font properties. This is convenient. 
Updated translations for the Russian and Kazakh languages, taking into account the new changes introduced.

### CODE REVIEW

**Comment by giuspen** [comment]
Hi Viktor, aren't superscript and subscript also font properties? Maybe the submenu item label should be for consistency 'Toggle Font Property' rather than just 'Font Property' since it's toggling stuff too?

**Comment by Camilot55** [comment]
Hi, Giuseppe. Okay, I'll fix it now. Let's do this. I agree.

**Comment by Camilot55** [comment]
Giuseppe will there be any more new items to translate?
 If not, then I make a neat translation into two languages, taking into account the new one.

**Comment by giuspen** [comment]
Yes Viktor there will be a couple of more strings to translate related to the user configurable h1...h6 (preferences dialog new tab 'Format'), that I will try to complete this evening anyway, after that string freeze until after 0.99.34

**Comment by Camilot55** [comment]
Well, then I will correct my mistakes, make your suggestions and post new files.

**Comment by giuspen** [comment]
I will let you finish your part before strings freeze no worries

**Comment by Camilot55** [comment]
OK thanks

**Comment by Camilot55** [comment]
Updated the file with comments and a new cherrytree.pot

**Comment by giuspen** [comment]
I merged manually thanks, the languages .po files were not merged because not 100%. Going to write a mail to all the translators in a moment with all the files to update attached for upcoming 0.99.34

**Pull request closed without merging**
