### PR TITLE
Redesign pdf exporting code

### PR DESCRIPTION
**Pull request by ForeverRainbow**
This is the first part to implementing: #942 

I ended up going for the redesign in the end because the custom formatting worked up to a point but was incredibly hacky and trying to get it to align properly and format correctly was a nightmare. 

The new design works as follows:
- `CtPrintData` has a list of `CtPrintable`'s which are everything which can be drawn to the pdf  (i.e text and widgets). 
- Page count is calculated based on the sum heights of all the `CtPrintable`'s in the print data divided by the size of each page (rounded up, +1 if there is any remainder)
- `CtPrintable` exposes `height()`, `width()`, `setup()`, `print()` and `done()`. `setup()` needs to be called before the printable can be used and `print()` displays the printable in the given context and returns the final position of the "cursor" after drawing the printable. `done()` is used to check if the printable is done (e.g the text printable will not be "done" until it has printed all of its line but it may print them over several pages).
- Page breaks are done via `CtPageBreakPrintable` which returns `-1` for the height (< 0 is interpreted as a page break) and moves the position of the cursor out of bounds on `print()`.
- Widget printables inherit from the template `CtWidgetPrintable`, which inherits from `CtPrintable`, based on their widget (e.g `CtWidgetTablePrintable` inherits from `CtWidgetPrintable<CtPrintTableProxy>`), the dynamic casts have been moved to `printable_from_widget()`. It may be possible to avoid the proxy classes all together here but I did not think it was really necessary. 

`_on_begin_print_text` now simply calls `setup()` on all the printables and calculates the number of pages (as described above). 

`_on_draw_page_text` now calls `print()` on the current printable and updates the next position based on the return value, if the printable is done it increments the current printable, if the new position after printing is larger than the height of the page it returns.

The pango serialization methods now all return either `std::vector<std::shared_ptr<CtPrintable>>` (`CtPrintableVector`) or `std::shared_ptr<CtPrintable>`.

Based on this structure it should be simple to implement links and anchors since `print()` gets the current position and a cairo context to use and each `CtPrintable` is completely independent.

### CODE REVIEW

**Comment by txe** [comment]
Proxy objects like CtPrintTableProxy was used to keep additional information without unnecessary changing widgets.
With CtWidgetPrintable they became unnecessary, and it doesn't have sense to have additional layer.

**Comment by txe** [comment]
`printable_from_widget` is used only in CtExport2Pango, why not to make it private and put it there?

**Comment by txe** [comment]
Though you are right, if you begin remove proxy code, the PR become less clear, so it's unecessary

**Comment by txe** [comment]
How heavy did you test changes? I think of just merging it and fixing some insignificant parts later.

**Comment by ForeverRainbow** [comment]
I tested them with a large tree (214 page for node on each page) and a single node with lots of newlines (to split text over pages). Also tested node with and without node in new page, exporting only selection, node and subnodes, and only this node. 

As far as I can tell the output is identical to the old output (except exporting only selection has an extra page I think).

**Comment by txe** [comment]
Ok, thanks!

**Pull request merged**
