### PR TITLE
Improve HTML output

### PR DESCRIPTION
**Pull request by ForeverRainbow**
This improves the styling of the output HTML, mostly it only uses `style3.css` but there is also some html injection using `script3.js`.

Changes:
- Tree panel can be shown/hidden using a button between it and the `page_frame` iframe, mousing over the button when closed will open it
- Background is now `#EEEEEE` for everything
- Backgrounds for widgets (i.e tables) is now `rgb(197, 197, 197)` (`#FFC1C1C1`)
- Links on the tree expand to the full width of the row and the row lights up (`rgba(197, 197, 197, 0.7)`) on mouse over instead of the link being underlined
- The `+/-` buttons on the tree no longer have borders and are vertically centred in the row
- The `index` text at the top of the tree panel has been moved up and made `h1`
- Buttons no longer have borders or backgrounds and instead their text is lightened when moused over
- Headers for node titles have been centred, moved up, and given a background so that they at least somewhat resemble the node headers in cherrytree
- Codeboxes are now `inline-block`, meaning they will resize to fit their contents instead of being the width of the page (with a minimum width of `30%`)
- Codeboxes and tables now have a black border instead of grey
- Tables now have solid borders instead of disjointed lines

I realise that users can do all of this themselves by changing `style3.css` and `script3.js` in the config folder but I think these are better "defaults" as it were. They will of course not take affect unless the user replaces their existing config files

I have also changed the C++ version when exporting tables to correct the issue of headers being all the far left cells instead of the first row and squashed table cells due to empty contents

### CODE REVIEW

**Comment by txe** [comment]
It looks ok, but did you try the output in different browsers?

**Comment by ForeverRainbow** [comment]
Tested it in chrome, chromium and firefox. As far as I can tell its identical across all of them

**Comment by txe** [comment]
@giuspen , I think files again have to change numbers 3 -> 4
Maybe we need to stop copying these files into user config

**Comment by giuspen** [comment]
@txe the issue is that some users want to be able to customize the stylesheet

**Comment by ForeverRainbow** [comment]
Maybe it could be changed to use the priority convention of numbers at the end, so `style-3.css`, would be included before `style-4.css` (and thereby overridden)

**Pull request merged**
