### PR TITLE
(Port to C++) cmake

### PR DESCRIPTION
**Pull request by txe**
(ref to keep progress: #444)

This PR:
- removes almost all autoconf files
- adds support for make install
- adds support for creating a package
- `export to html` takes files from share/cherrytree/data
- not done: currently working on how to update po files
- not done: readme is not updated (but renamed to README.md)
- ~~well, it will definitely break travis build~~
 
Here are some examples, it doesn't matter where keep working directory for cmake, e.g
```sh
mkdir cherrytree/build_dir
cd cherrytree/build_dir
```

To test locally `make install`
```sh
cmake -DCMAKE_INSTALL_PREFIX=./local_usr ../future
make -j4  && make install
```

To create a package for debian
```sh
cpack -G DEB
```

### CODE REVIEW

**Comment by giuspen** [comment]
Доброе утром @txe you can leave the language files to me unless already on it 😉

**Comment by txe** [comment]
Привет
Do we merge this pr?

**Comment by giuspen** [comment]
Absolutely thanks my unstoppable friend

**Comment by txe** [comment]
Ok, langs is on you , thanks

**Pull request merged**
