### PR TITLE
Update langs

### PR DESCRIPTION
**Pull request by Camilot55**
Обновил языки

### CODE REVIEW

**Comment by giuspen** [comment]
There is still one untranslated:
```
You must associate a command to '%s'.
Do so in the Preferences Dialog
```
image

**Comment by giuspen** [comment]
[kk_KZ.po.zip](https://github.com/giuspen/cherrytree/files/7656922/kk_KZ.po.zip)
this is the latest with 801 strings to translate and only 800 translated

**Comment by Camilot55** [comment]
Thanks. I'll fix it

**Comment by Camilot55** [comment]
Hi Giuseppe. 
Made by.

**Comment by giuspen** [comment]
Thanks Viktor!

**Pull request merged**
