### PR TITLE
(Port to C++) image popup menu

### PR DESCRIPTION
**Pull request by txe**
(ref to keep progress: #444)

- Finished popup menu actions for images
- Renamed  `get_tree_iter_from_node_id` to `get_node_from_node_id`, because every time I literately cannot find its name. 

I wonder how far away we are from making the program working? Maybe we can create some task list in #444 to visualize it?

### CODE REVIEW

**Comment by giuspen** [comment]
Hi @txe two mandatory steps are the save to sqlite and the undo/redo state machine where I wanted to focus now. I'm sorry I have not had much time recently while your progress has been so great. If you can make a summary please do, I'm not sure I will find the time these days to go through all the code; in the next 2 weeks I will be in Italy on holiday then Ukraine at in laws House - in Ukraine I should be able to do at least the write to sql and properly testing the writes to disk. Tomorrow morning uk time I'll try and release 0.38.9.

**Comment by txe** [comment]
OK, no problem. Then I will focus on codebox, table, source view behaviors.

**Comment by giuspen** [comment]
@txe if you send me a mail with your iban I'll buy you at least a dinner out for two 😉

**Comment by txe** [comment]
I'll keep that in mind 😄

**Pull request merged**
