### PR TITLE
Force turning off portal usage since it does not work on all distros

### LINKED ISSUE #2107: crash on import
**Version, Operative system**
`Ubuntu 20.04.4 LTS`

```
kevin@dogbert:~> snap list --all
Name                Version                     Rev    Tracking       Publisher    Notes
cherrytree          0.99.48                     56     latest/stable  hellsworth   -
cherrytree          0.99.48                     49     latest/stable  hellsworth   disabled
```
I tried reverting to revision 49 and the same problem happens.

**Describe the bug**
Cherrytree crashes when I try to do any import: html, text, html folder, etc. If run from a terminal then more info becomes visible:
kevin@dogbert:~> cherrytree
[2022-08-28 23:13:43.935] [   ] [debug] /home/kevin/snap/cherrytree/56/.config/cherrytree/config.cfg parsed
[2022-08-28 23:13:44.058] [   ] [debug] autosave is started
[2022-08-28 23:14:06.166] [   ] [debug] Node name: Technical
[2022-08-28 23:14:08.669] [   ] [debug] shift images in MenuBar/context menu
[2022-08-28 23:14:12.183] [gtk] [warning] Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
[2022-08-28 23:14:12.279] [gtk] [info] Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)

**To Reproduce**
1. Start Cherrytree.
2. Create a new node (optional, problem happens with or without this, but I'm listing this since I did it above and I wanted to make sure no nodes wasn't causing the issue).
3. Select File->Import->From_HTML_File (but I've seen it fail on at least 3 different file types so I think the problem is with the code when it tries any import) ... then it crashes.

If it wasn't obvious above, this is with the latest Ubuntu snap.
This is on a KDE desktop, but I have no problem running other GTK programs or snaps.

### PR DESCRIPTION
**Pull request by hellsworth**
Fixes #2107

### CODE REVIEW

**Comment by giuspen** [comment]
Thanks @hellsworth !

**Comment by hellsworth** [comment]
Forgot to say that it's available in --stable now.

**Comment by giuspen** [comment]
Thanks @hellsworth I did test on 18.04 after building locally and it worked fine, I'll try now to uninstall and reinstall from the store instead

**Comment by giuspen** [comment]
I was able to successfully open / edit / save in my tests but I realised it's failing to access mounted locations, in fact I see the following warning when running the File--Open dialog:

[2022-09-03 11:12:38.835] [gtk] [warning] Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

Maybe you can still help me with this? :)

**Comment by giuspen** [comment]
Export to PDF also crashes, I see another warning

** (cherrytree:6143): WARNING **: 11:19:56.352: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.118" (uid=1000 pid=6143 comm="/snap/cherrytree/58/bin/cherrytree " label="snap.cherrytree.cherrytree (enforce)") interface="org.freedesktop.Avahi.Server" member="ServiceBrowserNew" error name="(unset)" requested_reply="0" destination="org.freedesktop.Avahi" (uid=122 pid=798 comm="avahi-daemon: starting up " label="unconfined")

**Comment by giuspen** [comment]
Weirdly if I build the snap myself and install that, I have not the warnings reported above and all works perfectly

**Comment by giuspen** [comment]
Thanks @hellsworth I will raise another ticket after additional tests

**Pull request merged**
