### PR TITLE
Fix visited nodes history going to todays node using key binding

### PR DESCRIPTION
**Pull request by ksmukta**
**Ctrl+T** is mapped to **Insert Today's Node**

**Before Fix**: Going to today's node adds Year, Month and Day nodes to visited history.
before_fix_history

**After Fix**: Just add Day node to visited nodes history.
after_fix_history

### CODE REVIEW

**Comment by txe** [comment]
Can I suggest how to improve? I'm busy for now, but in couple of hours I will write how it can look.

**Comment by txe** [comment]
1. `node_date` can be simplified and that will make easier to add your changes , try code from #434 .
2. before creating nodes, made a copy of `self.visited_nodes_list`
3. optional: after creating `year` and `month` nodes, remove their ids from a **copy** of `self.visited_node_list`
4. restore `self.visited_node_list` and create the last node

I think, it should work

**Comment by txe** [comment]
Nice gifs, btw! If only everyone could add them in their issues :)

**Comment by ksmukta** [comment]
> Nice gifs, btw! If only everyone could add them in their issues :)

Lol, thanks for noticing, takes time but makes things crystal clear.

**Comment by ksmukta** [comment]
> 1. `node_date` can be simplified and that will make easier to add changes , try code from #434 .

I have created a pull request for this #638

**Comment by ksmukta** [comment]
Closing this, fix pushed in #638

**Pull request closed without merging**
